### ISSUE TITLE
LoadError: cannot load such file -- ./_sass/bourbon/lib/bourbon.rb

### ISSUE THREAD

**Issue by ericclemmons** [tybenz/exemplar#1]
Idears? 

```
$ rake watch
Starting to watch source with Jekyll and Sass...
LoadError: cannot load such file -- ./_sass/bourbon/lib/bourbon.rb
  Use --trace for backtrace.
LoadError: cannot load such file -- ./_sass/bourbon/lib/bourbon.rb
  Use --trace for backtrace.
       Deprecation: Jekyll now uses subcommands instead of just switches. Run `jekyll help' to find out more.
       Deprecation: The --server command has been replaced by the 'serve' subcommand.
       Deprecation: The switch '--auto' has been replaced with '--watch'.
invalid option: --auto
```

**Comment by soniajoseph** [comment]
Hi, cd into _sass and bourbon install does not fix this:

** Invoke default (first_time)
** Invoke watch (first_time)
** Execute watch
Starting to watch source with Jekyll and Sass...
LoadError: cannot load such file -- ./_sass/bourbon/lib/bourbon.rb
  Use --trace for backtrace.
/usr/local/var/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/liquid-2.4.1/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
LoadError: cannot load such file -- ./_sass/bourbon/lib/bourbon.rb
  Use --trace for backtrace.
