### ISSUE TITLE
Rakefile not found

### ISSUE THREAD

**Issue by bretonio** [tybenz/exemplar#4]
No Rakefile found ...

**Comment by tybenz** [comment]
I need more details here. There is a Rakefile in the repo, so if your installation of ruby or rake can't find it, it's probably something wrong with your environment specifically.

**Comment by bretonio** [comment]
Probably. I will read the Archlinux wiki. More info when I get a chance.
Thank you!

**Comment by bretonio** [comment]
Complaints about versions installed. I followed some forum advice, ran a couple of bundle updates and prefaced `rake` with `bundle exec` like I ought to and pimba! Thanks.
